### ISSUE TITLE
SDRS issue when more than one protected instance or protection group

### ISSUE THREAD

**Issue by nsabernierdev1** [FlexibleEngineCloud/terraform-provider-flexibleengine#317] opened 2020-03-04 10:07 UTC
Hi there,

### Terraform Version
12.18

### Affected Resource(s)
- sdrs_protectiongroup
- sdrs_protectedinstance

### Steps to Reproduce
Crate a terraform project with two protection group or/and two protection instances
1. `terraform apply`
2. `terraform plan`
It always says it wants to recreate the second group or second instance

**Comment by niuzhenguo** [comment] 2020-03-05 06:21
@nsabernierdev1 Can you provide more information? like which field causes the recreation.

**Comment by sbernier-corp** [comment] 2020-03-05 09:25
Yes, here is the ouput:
Terraform will perform the following actions:
  # flexibleengine_sdrs_protectedinstance_v1.instance_redis must be replaced
-/+ resource "flexibleengine_sdrs_protectedinstance_v1" "instance_redis" {
      + description   = "server redis" # forces replacement
      + group_id      = "1b7bb5e2-3420-4e87-a782-72e639d0d9eb" # forces replacement
      ~ id            = "564206c7-a5c1-4b0c-bef6-11b94c8d54c5" -> (known after apply)
      + name          = "instance_redis"
        server_id     = "4d8a7091-aa38-4044-bddc-61b47ebd65c0"
      + target_server = (known after apply)
    }
Plan: 1 to add, 0 to change, 1 to destroy.

**Comment by sbernier-corp** [comment] 2020-03-09 13:36
Hi,
After looking into the terraform logs, I noticed that the issue is at the API level and not at the provider level.

The issue is coming from the fact that the second parrallel get command response is empty.

I will open a case at Flexible engine support.

As a temporary workaround I have added a depends_on beween SDRS resources.

Thanks,

**Comment by niuzhenguo** [comment] 2020-03-10 01:29
@antonin-a @DafuSHI ^

**Comment by DafuSHI** [comment] 2020-03-15 21:14
I'm asking R&D SDRS taking a look, will give a feedback soon

**Comment by sbernier-corp** [comment] 2020-03-20 12:43
Any feedback ?

**Comment by ShiChangkuo** [comment] 2023-06-21 08:07
@sbernier-corp @nsabernierdev1 It seems that the issue wad fixed by API server, please try it again.

**Comment by ShiChangkuo** [comment] 2023-07-10 02:24
I will close it temporarily. If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Closed by ShiChangkuo** 2023-07-10 02:24 UTC
Labels: waiting-response, api issue
